<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SDVE" nsURI="SDVE" nsPrefix="SDVE">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="DVE" value="platform:/resource/dve-model/model/DVE.ecore"/>
    <details key="model_0" value="../../dve-model/model/DVE.ecore#//model"/>
  </eAnnotations>
  <eSubpackages name="model" nsURI="smodel" nsPrefix="model">
    <eClassifiers xsi:type="ecore:EClass" name="SElement" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Element #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" ordered="false"
          upperBound="-1" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/NamedDeclaration"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" ordered="false"
          upperBound="-1" eType="#//model/AbstractTransition" containment="true">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="acceptingConditions"
          ordered="false" upperBound="-1" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Expression"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
          eType="#//model/SystemProperties" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemProperties" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Element #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemType" lowerBound="1"
          eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/SystemType"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractTransition" abstract="true"
        eSuperTypes="../../dve-model/model/DVE.ecore#//model/Element #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="process" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effect" ordered="false"
          upperBound="-1" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Assignment"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//model/AbstractTransition #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sync" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Synchronization"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FlatTransition" eSuperTypes="#//model/AbstractTransition #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardBlock" ordered="false"
          upperBound="-1" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Assignment"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateType" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Type #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//model/State" containment="true">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//model/State"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="../../dve-model/model/DVE.ecore#//model/State #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="committed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TupleType" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Type #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" ordered="false"
          lowerBound="1" upperBound="-1" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Type"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BufferType" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Type #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BufferRead" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Expression #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/VariableReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BufferWrite" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Assignment #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/VariableReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BufferIsEmpty" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Expression #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/VariableReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BufferIsFull" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Expression #//model/SElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" eType="ecore:EClass ../../dve-model/model/DVE.ecore#//model/VariableReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BitType" eSuperTypes="../../dve-model/model/DVE.ecore#//model/Type #//model/SElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TransientVariableDeclaration" eSuperTypes="../../dve-model/model/DVE.ecore#//model/VariableDeclaration #//model/SElement"/>
  </eSubpackages>
</ecore:EPackage>
